---
version: '3'
services:
  redis:
    image: redis:5.0.9
    environment:
      LANG: "C.UTF-8"
    command: >
      redis-server
        --maxmemory        256mb
        --maxmemory-policy noeviction
        --appendonly       yes
    volumes:
      - "/var/tmp/reudy-redis:/data"
  reudy:
    image: ghcr.io/supercaracal/reudy:latest
    environment:
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - "/var/tmp/reudy:/opt/app/public"
    depends_on:
      - redis
  bot:
    image: ghcr.io/supercaracal/tkkz-bot:latest
    environment:
      TZ: "Asia/Tokyo"
      SLACK_TOKEN: "${SLACK_TOKEN}"
      BOT_ID: "${BOT_ID}"
      SLACK_APP_TOKEN: "${SLACK_APP_TOKEN}"
      SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}"
      BRAIN_URL: "http://reudy:3000"
    depends_on:
      - reudy
networks:
  default:
    ipam:
      config:
        - subnet: "172.20.13.0/28"
