---
version: '3'
services:
  redis:
    image: redis:5.0.9
    environment:
      TZ: "${TZ}"
      LANG: "C.UTF-8"
    command: >
      redis-server
        --maxmemory        256mb
        --maxmemory-policy noeviction
        --appendonly       yes
    volumes:
      - "/var/tmp/reudy-redis:/data"
  mackerel-agent:
    image: mackerel/mackerel-agent:latest
    environment:
      TZ: "${TZ}"
      apikey: "${MACKEREL_API_KEY}"
      include: "/etc/mackerel-agent/conf.d/*.conf"
    volumes:
      - "/var/tmp/reudy-redis-mackerel:/var/lib/mackerel-agent"
      - "./config/mackerel-agent:/etc/mackerel-agent/conf.d:ro"
    depends_on:
      - redis
  reudy:
    image: ghcr.io/supercaracal/reudy:latest
    environment:
      TZ: "${TZ}"
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - "/var/tmp/reudy:/opt/app/public"
    depends_on:
      - redis
  bot:
    image: ghcr.io/supercaracal/tkkz-bot:latest
    environment:
      TZ: "${TZ}"
      SLACK_TOKEN: "${SLACK_TOKEN}"
      BOT_ID: "${BOT_ID}"
      SLACK_APP_TOKEN: "${SLACK_APP_TOKEN}"
      SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}"
      BRAIN_URL: "http://reudy:3000"
    depends_on:
      - reudy
networks:
  default:
    ipam:
      config:
        - subnet: "172.20.13.0/28"
