---
version: "3"
services:
  brain:
    image: "redis"
    restart: "always"
  hubot:
    build:
      context: "./docker/hubot"
      args:
        - "REPOSITORY_URL=https://github.com/supercaracal/tkkz-bot.git"
    depends_on:
      - "brain"
    restart: "always"
    environment:
      - "REDIS_URL=redis://brain:6379/hubot"
      - "HUBOT_SLACK_TOKEN=${HUBOT_SLACK_TOKEN}"
      - "HUBOT_GOOGLE_CSE_KEY=${HUBOT_GOOGLE_CSE_KEY}"
      - "HUBOT_GOOGLE_CSE_ID=${HUBOT_GOOGLE_CSE_ID}"
      - "HUBOT_YOUTUBE_API_KEY=${HUBOT_YOUTUBE_API_KEY}"
