---
version: '3'
services:
  redis:
    image: redis:5.0.9
    environment:
      LANG: "C.UTF-8"
    command: >
      redis-server
        --maxmemory        256mb
        --maxmemory-policy noeviction
        --appendonly       yes
    volumes:
      - "${REDIS_DATA_PATH}:/data"
    ports:
      - "${REDIS_PORT}:6379"
  reudy:
    image: ghcr.io/supercaracal/reudy:latest
    environment:
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - "${BRAIN_DATA_PATH}:/opt/app/public"
    depends_on:
      - redis
    ports:
      - "${BRAIN_PORT}:3000"
networks:
  default:
    ipam:
      config:
        - subnet: "172.20.14.0/28"
