---
version: '3'
services:
  reudy:
    image: ghcr.io/supercaracal/reudy:latest
#   ports:
#     - "3000:3000"
    volumes:
      - "/var/tmp/reudy:/opt/app/public"
  bot:
    image: ghcr.io/supercaracal/tkkz-bot:latest
    env_file:
      - ".env"
networks:
  default:
    ipam:
      config:
        - subnet: "172.20.13.0/28"
