---
version: "3"
services:
  brain:
    build: "docker/brain"
    restart: "always"
    volumes:
      - "${SRC_DIR}/data:/data"
  hubot:
    build: "docker/hubot"
    restart: "always"
    depends_on:
      - "brain"
    volumes:
      - "${SRC_DIR}:/opt/tkkz-bot"
    environment:
      - "REDIS_URL=redis://brain:6379/hubot"
      - "HUBOT_SLACK_TOKEN=${HUBOT_SLACK_TOKEN}"
      - "HUBOT_GOOGLE_CSE_KEY=${HUBOT_GOOGLE_CSE_KEY}"
      - "HUBOT_GOOGLE_CSE_ID=${HUBOT_GOOGLE_CSE_ID}"
      - "HUBOT_YOUTUBE_API_KEY=${HUBOT_YOUTUBE_API_KEY}"
